import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/modules/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  );
}
